// <auto-generated />
using System;
using GD.RequestSystem.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GD.RequestSystem.DAL.Migrations
{
    [DbContext(typeof(RequestSystemDbContext))]
    partial class RequestSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GD.RequestSystem.Entities.Catalogs.Area", b =>
                {
                    b.Property<int>("AreaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaID"), 1L, 1);

                    b.Property<string>("AreaKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreaterID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeleterID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdaterID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("AreaID");

                    b.ToTable("tblAreas", (string)null);
                });

            modelBuilder.Entity("GD.RequestSystem.Entities.Petition", b =>
                {
                    b.Property<int>("PetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetitionID"), 1L, 1);

                    b.Property<int?>("AreaID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreaterID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeleterID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdaterID")
                        .HasColumnType("int");

                    b.Property<string>("MessagePetition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PetitionStatus")
                        .HasColumnType("int");

                    b.Property<string>("PetitionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("urlDocumentPetition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userAsignedID")
                        .HasColumnType("int");

                    b.Property<int>("userCreateID")
                        .HasColumnType("int");

                    b.HasKey("PetitionID");

                    b.ToTable("tblPetition", (string)null);
                });

            modelBuilder.Entity("GD.RequestSystem.Entities.PetitionStatus", b =>
                {
                    b.Property<int>("PetitionStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetitionStatusID"), 1L, 1);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreaterID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeleterID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdaterID")
                        .HasColumnType("int");

                    b.Property<string>("PetitionStatusKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetitionStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("PetitionStatusID");

                    b.ToTable("tblPetitionStatus", (string)null);
                });

            modelBuilder.Entity("GD.RequestSystem.Entities.ResultPetition", b =>
                {
                    b.Property<int>("ResultPetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultPetitionID"), 1L, 1);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreaterID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateTimeResponse")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeleterID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdaterID")
                        .HasColumnType("int");

                    b.Property<string>("MessageResponce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetitionId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UrlDocumentResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userResponceID")
                        .HasColumnType("int");

                    b.HasKey("ResultPetitionID");

                    b.ToTable("tblResultPetition", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
